### ISSUE TITLE
Stone Block doesn't work for large houses

### ISSUE THREAD

**Issue by CrackerHax** [EmpireMUD/EmpireMUD-2.0-Beta#129]
It says "large stone block" which I assume is different from "huge stone block". Anyway huge stoneblock won't work and I have found no way to make "large stone block".

**Comment by EmpireMUD** [comment]
The large house requires the component (bunch block), which large stone blocks don't satisfy. The best "bunch" of blocks right now is bricks.

**Comment by CrackerHax** [comment]
It would be great if the separate command worked for huge block to make them into smaller ones and large leathers to make them into small leathers.
