### ISSUE TITLE
Should ships sail at different speeds?

### ISSUE THREAD

**Issue by luciensadi** [EmpireMUD/EmpireMUD-2.0-Beta#251]
Currently, my understanding is that all ships sail at the same speed, whether they're hand-paddled canoes, overloaded cargo ships, or fast longships. If you're interested, I can look into making the ships sail at different speeds-- perhaps with a multiplier stored in the ship's data that dictates how often it sails?

Also, is sailing intended to proceed at half speed if you're hungry or thirsty?

**Comment by EmpireMUD** [comment]
#1 Yes I like the idea of variable vehicle speeds. This has come up before and I'd like to discuss exactly how to change it. My initial reaction would be to slow down canoes but add a way to speed up premium ships, while most or all of the non-adventure ships would keep their current speed.

#2 Yes all timed actions are penalized when you're hungry/thirsty/starved. For ships, I imagine it like you're inefficient and forgetting important parts of sailing and that is slowing you down. But mostly it's a game penalty for not taking care of your character (and players can easily work around it with abilities like Sated Thirst if they don't like self-care).

**Comment by EmpireMUD** [comment]
Closing this as the work is done.
