### ISSUE TITLE
Send ROOM MSDP variables immediately upon moving, rather than queuing once per second like normal

### ISSUE THREAD

**Issue by lilmike** [EmpireMUD/EmpireMUD-2.0-Beta#260]
I'm working on updating the tintin pack (https://github.com/stormdragon2976/tintin-empiremud) to be more immercive, and one of the issues I'm running into is getting a reliable notification that the room has changed, and what the name is. Currently we use the coordinates at the end of a line to anchor a trigger to extract the room name, but that can be misinterpreted by things such as the city list on the chart command, along with requiring navigation to work at all.
My idea was that the ROOM (and ROOM_X) variables in MSDP could be explicitly flushed when you move rooms (I believe there's a function to do that already in the MSDP snippet), and then the pack could know explicitly when you have moved rooms, and what you have moved to.
-Michael.

**Comment by EmpireMUD** [comment]
This is done and will be in b5.38 next week. Let me know when you're around and I'll set up a staging server for it.
